const theme=document.getElementById("theme");
const nav=document.querySelector(".nav");
const menu=document.querySelector(".menu");
if(localStorage.getItem("theme")==="dark") document.body.classList.add("dark");
function icon(){theme.textContent=document.body.classList.contains("dark")?"☾":"☼"} icon();
theme.onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("theme",document.body.classList.contains("dark")?"dark":"light");icon()};
menu.onclick=()=>nav.classList.toggle("open");
document.querySelectorAll(".nav a").forEach(a=>a.onclick=()=>nav.classList.remove("open"));
document.getElementById("year").textContent=new Date().getFullYear();
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.12});
document.querySelectorAll(".reveal").forEach(x=>obs.observe(x));